disabled_rules:
    - trailing_whitespace
    - line_length
    - force_cast
    - function_body_length
excluded:
    - Pods
    - Carthage
force_try:
    severity: warning
variable_name:
    min_length: 1
